#include "usart.h"
void USART_Init(){
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	RCC->AHBENR |= RCC_AHBENR_GPIODEN;
	
	RCC->APB1ENR |= RCC_APB1ENR_USART3EN;
	
	// PC10 - USART3_TX
	// PC11 - USART3_RX
	// PD2 - USART3_RTS
	GPIOC->AFR[1] |= (1 << 4 * (10 - 8)) | (1 << 4 * (11 - 8));
    GPIOC->MODER |= GPIO_MODER_MODER10_1 | GPIO_MODER_MODER11_1;

	GPIOD->AFR[0] |= 1  << 4 * 2;
	GPIOD->MODER |= GPIO_MODER_MODER2_1;
	
	USART3->BRR = 480000 / 96;
	USART3->CR3 |= USART_CR3_DEM | USART_CR3_OVRDIS;
	
	USART3->CR1 |= USART_CR1_DEAT_0 | USART_CR1_DEAT_1 | USART_CR1_DEAT_2 | USART_CR1_DEAT_3 | USART_CR1_DEAT_4;
	USART3->CR1 |= USART_CR1_DEDT_0 | USART_CR1_DEDT_1 | USART_CR1_DEDT_2 | USART_CR1_DEDT_3 | USART_CR1_DEDT_4;
	
	USART3->CR1 = USART_CR1_UE | USART_CR1_TE | USART_CR1_RE;
	
}
